version: '3'
services:

  broker-fuseki:
    image: registry.gitlab.cc-asp.fraunhofer.de/eis-ids/broker-open/fuseki
    environment:
    - ADMIN_PASSWORD=test
    ports:
    - "3030:3030"
    volumes:
      - broker-fuseki:/fuseki

volumes:
    broker-fuseki:
